version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend
    restart: unless-stopped
    env_file: .env
    ports:
      - '3000:3000'
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

  frontend:
    build:
      context: ./frontend
      dockerfile: docker/Dockerfile
    tty: true
    stdin_open: true
    ports:
      - '8080:8080'
    volumes:
      - ./frontend:/app

volumes:
  mongo-data: